/* tslint:disable */
/* eslint-disable */
/**
 * Library API
 * API documentation for the book Library API
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
  AuthorManagementApiFactory,
  BookManagementApiFactory,
  CountryManagementApiFactory,
  UserAPIApiFactory,
} from "./api";
import { Configuration } from "./configuration";

export * from "./api";
export * from "./configuration";

const config = new Configuration({
  basePath: "http://localhost:8080",
  baseOptions: {
    headers: {
      Authorization: `Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlcyI6WyJBRE1JTiJdLCJzdWIiOiJhZG1pbiIsImlhdCI6MTc0NzA2ODk2OSwiZXhwIjoxNzQ3OTMyOTY5fQ.-Kva2kxekL_NaZ62ED-dqHyIg5amrlAhK2pYiD5HmLY`,
    },
  },
});

export const countriesApi = CountryManagementApiFactory(config);
export const usersApi = UserAPIApiFactory(config);
export const authorsApi = AuthorManagementApiFactory(config);
export const booksApi = BookManagementApiFactory(config);
