CREATE TABLE author
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255),
    surname    VARCHAR(255),
    country_id BIGINT,
    CONSTRAINT pk_author PRIMARY KEY (id)
);

CREATE TABLE book
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name             VARCHAR(255),
    category         VARCHAR(255),
    author_id        BIGINT,
    available_copies INTEGER,
    CONSTRAINT pk_book PRIMARY KEY (id)
);

CREATE TABLE book_rental
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    book_id       BIGINT,
    user_username VARCHAR(255),
    CONSTRAINT pk_bookrental PRIMARY KEY (id)
);

CREATE TABLE country
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name      VARCHAR(255),
    continent VARCHAR(255),
    CONSTRAINT pk_country PRIMARY KEY (id)
);

CREATE TABLE users
(
    username                   VARCHAR(255) NOT NULL,
    password                   VARCHAR(255),
    name                       VARCHAR(255),
    surname                    VARCHAR(255),
    is_account_non_expired     BOOLEAN      NOT NULL,
    is_account_non_locked      BOOLEAN      NOT NULL,
    is_credentials_non_expired BOOLEAN      NOT NULL,
    is_enabled                 BOOLEAN      NOT NULL,
    role                       VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (username)
);

CREATE TABLE wishlist
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_username VARCHAR(255),
    CONSTRAINT pk_wishlist PRIMARY KEY (id)
);

CREATE TABLE wishlist_books
(
    wishlist_id BIGINT NOT NULL,
    books_id    BIGINT NOT NULL
);

ALTER TABLE author
    ADD CONSTRAINT FK_AUTHOR_ON_COUNTRY FOREIGN KEY (country_id) REFERENCES country (id);

ALTER TABLE book_rental
    ADD CONSTRAINT FK_BOOKRENTAL_ON_BOOK FOREIGN KEY (book_id) REFERENCES book (id);

ALTER TABLE book_rental
    ADD CONSTRAINT FK_BOOKRENTAL_ON_USER_USERNAME FOREIGN KEY (user_username) REFERENCES users (username);

ALTER TABLE book
    ADD CONSTRAINT FK_BOOK_ON_AUTHOR FOREIGN KEY (author_id) REFERENCES author (id);

ALTER TABLE wishlist
    ADD CONSTRAINT FK_WISHLIST_ON_USER_USERNAME FOREIGN KEY (user_username) REFERENCES users (username);

ALTER TABLE wishlist_books
    ADD CONSTRAINT fk_wisboo_on_book FOREIGN KEY (books_id) REFERENCES book (id);

ALTER TABLE wishlist_books
    ADD CONSTRAINT fk_wisboo_on_wishlist FOREIGN KEY (wishlist_id) REFERENCES wishlist (id);